// This file was (mostly) ripped from https://duckduckgo.com/bang.js

export const bangs = [
  {
    c: "AI",
    d: "www.t3.chat",
    r: 0,
    s: "T3 Chat",
    sc: "AI",
    t: "t3",
    u: "https://www.t3.chat/new?q={{{s}}}",
  },
  {
    c: "Online Services",
    d: "www.google.com",
    r: 1942262,
    s: "Google",
    sc: "Google",
    t: "g",
    u: "https://www.google.com/search?q={{{s}}}",
  },
  {
    c: "Online Services",
    d: "en.wikipedia.org",
    r: 189946,
    s: "Wikipedia",
    sc: "Search",
    t: "w",
    u: "https://en.wikipedia.org/wiki/Special:Search?search={{{s}}}",
  },
  {
    c: "Online Services",
    d: "google.com",
    r: 52329,
    s: "Google Images",
    sc: "Google",
    t: "gi",
    u: "https://google.com/search?tbm=isch&q={{{s}}}&tbs=imgo:1",
  },
  {
    c: "Online Services",
    d: "www.thesaurus.com",
    r: 526,
    s: "Thesaurus.com",
    sc: "Tools",
    t: "thesaurus",
    u: "https://www.thesaurus.com/browse/{{{s}}}?s=t",
  },
  {
    c: "Research",
    d: "www.thesaurus.com",
    r: 270,
    s: "Thesaurus",
    sc: "Reference (words)",
    t: "thes",
    u: "http://www.thesaurus.com/browse/{{{s}}}",
  },
  {
    c: "Research",
    d: "www.merriam-webster.com",
    r: 8,
    s: "Merriam-Webster",
    sc: "Reference (words)",
    t: "say",
    u: "https://www.merriam-webster.com/dictionary/{{{s}}}",
  },
  {
    c: "Research",
    d: "www.acronymfinder.com",
    r: 51,
    s: "Acronyms",
    sc: "Reference (words)",
    t: "acro",
    u: "http://www.acronymfinder.com/~/search/af.aspx?string=exact&Acronym={{{s}}}",
  },
  {
    c: "Online Services",
    d: "translate.google.com",
    r: 44,
    s: "Google Translate to English",
    sc: "Google",
    t: "ten",
    u: "https://translate.google.com/?hl=en&tab=TT#auto/en/{{{s}}}",
  },
  {
    c: "Online Services",
    d: "maps.google.com",
    r: 2271,
    s: "Google Maps",
    sc: "Google",
    t: "gmap",
    u: "http://maps.google.com/maps?q={{{s}}}",
  },
  {
    c: "Multimedia",
    d: "www.youtube.com",
    r: 463021,
    s: "YouTube",
    sc: "Video",
    t: "yt",
    u: "https://www.youtube.com/results?search_query={{{s}}}",
  },
  {
    c: "Online Services",
    d: "www.google.com",
    r: 48,
    s: "Google (Past 24h)",
    sc: "Google",
    t: "g24",
    u: "http://www.google.com/search?q={{{s}}}&tbs=qdr:d",
  },
];
